// Code generated by mockery v2.9.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AuthLogger is an autogenerated mock type for the AuthLogger type
type AuthLogger struct {
	mock.Mock
}

// Error provides a mock function with given fields: args
func (_m *AuthLogger) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Errorf provides a mock function with given fields: format, args
func (_m *AuthLogger) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Tracef provides a mock function with given fields: format, args
func (_m *AuthLogger) Tracef(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
