// Code generated by mockery v2.9.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RequestContext is an autogenerated mock type for the RequestContext type
type RequestContext struct {
	mock.Mock
}

// AbortWithStatusJSON provides a mock function with given fields: code, jsonObj
func (_m *RequestContext) AbortWithStatusJSON(code int, jsonObj interface{}) {
	_m.Called(code, jsonObj)
}

// GetHeader provides a mock function with given fields: key
func (_m *RequestContext) GetHeader(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *RequestContext) Next() {
	_m.Called()
}
